// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkwylu7uZurrRN6R_rjPOpa1jAKuJKnsE',
    appId: '1:6989757704:web:947da838f1a2aa789f00bd',
    messagingSenderId: '6989757704',
    projectId: 'together-the-game',
    authDomain: 'together-the-game.firebaseapp.com',
    storageBucket: 'together-the-game.appspot.com',
    measurementId: 'G-NJDVMCSQ8L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApVdBpEryHMm9H-QdKCI7FPU4Mag-WOiE',
    appId: '1:6989757704:android:e45743b46e19fad09f00bd',
    messagingSenderId: '6989757704',
    projectId: 'together-the-game',
    storageBucket: 'together-the-game.appspot.com',
  );
}
